version: "3"
services:
  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-time-zone='+9:00'"
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: samplesample
    volumes:
      - mysql-data:/var/lib/mysql
  sample:
    build: .
    ports:
      - '80:80'
    environment:
      DD_AGENT_HOST: datadog
      DBUSER: sample
      DBPASS: samplesample
      DBADDRESS: mysql
      DBPORT: 3306
      DBNAME: sample
    restart: always
    depends_on:
      - mysql
  datadog:
    image: datadog/docker-dd-agent
    links:
      - sample
      - mysql
    environment:
      - API_KEY=<APIKEY>
      - DD_APM_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/mounts:/host/proc/mounts:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126/tcp"

volumes:
  mysql-data:
